name: Condition2 message

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Print test
      run: |
        echo "Job Test"

  deploy:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'wifi')

    steps:
    - name: Deploy
      run: |
        echo "Deploying because commit message contains 'wifi'"
